class Trie:
    def __init__(self):
        ...

    def insert(self, s: str) -> None:
        ...

    def search(self, s: str) -> bool:
        ...

    def check_prefix(self, prefix: str) -> bool:
        ...

    def delete(self, s: str) -> bool:
        ... 